# General.
title: "TidyBlocks"
year: 2020
repo: "https://github.com/gvwilson/yem"

# Jekyll settings.
repository: <USERNAME>/<PROJECT>
defaults:
- scope:
    path: ""
  values:
    layout: "page"
kramdown:
  toc_levels: "2"
exclude:
- README.md
- coverage
- node_modules
- package-lock.json
- package.json
- test
